# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PageToObserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_to_login', models.TextField()),
                ('login_data', models.TextField()),
                ('data_to_observer', models.TextField()),
                ('last_page_content', models.TextField()),
                ('currently_observed', models.BooleanField(default=True)),
                ('refresh_period', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('displayed', models.BooleanField(default=False)),
                ('result', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebNotifier.PageToObserve')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registration', models.DateTimeField()),
                ('account_type', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pagetoobserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebNotifier.UserProfile'),
        ),
        migrations.AddField(
            model_name='appliances',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebNotifier.UserProfile'),
        ),
    ]
